In [7]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
x.shape # 
# shape describes how many data (or the range) along each available axis.2 elements in first axis and 3 elements along second axis
# In Numpy dimensions are called axes. The number of axes is rank.
# the nth coordinate to index an array in Numpy. And multidimensional arrays can have one index per axis.
# shape might be more accurately described as an attribute than as a function, since it is not invoked using function-call syntax

(2, 3)

In [11]:
x[1,0] # element along 1st axes and then element along 2nd axes

4

In [12]:
# In numpy arrays, dimensionality refers to the number of axes needed to index it,
#not the dimensionality of any geometrical space. 
#For example, you can describe the locations of points in 3D space with a 2D array
x=np.array([[1,2,3],[4,5,6]])
x
# it can describe 3D space because the length of each row (axis 1) is 3,
#so each row can be the x, y, and z component of a point's location. 
#The length of axis 0 indicates the number of points (here, 2). 
# axis=0/index/rows;
#column with axis=1/columns

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
y=np.array([[[1,2],[3,4]],[[0,6],[,8]]]) #3-d array.  
y


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
y.shape

(2, 2, 2)

In [28]:
y[0]

array([[1, 2],
       [3, 4]])

In [30]:
y[1]

array([[1, 2],
       [3, 4]])

In [40]:
y[0][0]


array([1, 2])

In [34]:
y[0,0]

array([1, 2])

In [36]:
y[0,0,0]

1

In [39]:
np.sum(y, axis=0)

array([[ 6,  8],
       [10, 12]])