In [4]:

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

def distances(a, b):
    return np.linalg.norm(a-b), cosine_similarity([a, b])[0][1]

def mixed(n_zeros, n_ones):
    return np.concatenate((np.repeat([1], n_ones), np.repeat([0], n_zeros)), axis=0)

def ones(n_ones):
    return np.repeat([1], n_ones)

print (distances(mixed(2, 2), ones(4)))
print (distances(mixed(3, 3), ones(6)))
print (distances(mixed(50, 50), ones(100)))
print (distances(mixed(300, 300), ones(600)))

print()

(1.4142135623730951, 0.7071067811865475)
(1.7320508075688772, 0.7071067811865477)
(7.0710678118654755, 0.7071067811865477)
(17.320508075688775, 0.7071067811865462)


In [5]:
# The euclidean distance for the 600 item vector is
#17x larger than for the one containing 4 items despite having the same similarity score.
#x=(2,2) and y=(1,1)- euclidean distance= 1.14
#x=(2,2,2) and y=(1,1,1)-euclidean distance=1.73
#x=x=(2,2,2,2)and y=(1,1,1,1)euclidean distance=2

In [48]:
# Truncated SVD
from sklearn.decomposition import TruncatedSVD

n_components = 2
reducer = TruncatedSVD(n_components=n_components)
reducer.fit(all)
new_all = reducer.transform(all)
print((n_components, reducer.explained_variance_ratio_.sum()))
#not working


In [14]:
(mixed(2, 2))

array([1, 1, 0, 0])

In [23]:
np.linalg.norm(mixed(2, 2))

1.4142135623730951

In [15]:
(mixed(2, 2)).shape

(4,)

In [20]:
ones(4)
ones(4).shape


(4,)

In [21]:
ones(4).reshape(2,2).shape

(2, 2)

In [24]:
mixed(50, 50)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
 a = np.arange(9) - 4
a

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [29]:
b=a.reshape((3, 3))
b

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [34]:
c=b.reshape(1,9)
c

array([[-4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [36]:
d=c.reshape(9,1)
d

array([[-4],
       [-3],
       [-2],
       [-1],
       [ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4]])

In [43]:
e=d.reshape(9,)
print(e)
print(a)
e==a

[-4 -3 -2 -1  0  1  2  3  4]
[-4 -3 -2 -1  0  1  2  3  4]


array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [44]:
print(c.shape)
print(d.shape)
print(e.shape)

(1, 9)
(9, 1)
(9,)


In [32]:
np.linalg.norm(a) #sqrt(60)

7.745966692414834

In [33]:
np.linalg.norm(b)#sqrt(60)

7.745966692414834