In [1]:
import numpy as np


In [2]:
# You are given 5 cylindrical containers with different radius and heights ranging between 5 and 25 cm. Find out
# a) the volume of water that each container can contain,
# b) the total volume of water that all containers can contain,
# c) which container can hold the highest volume and how much,
# d) which container can hold the least volume and how much,
# e) what is the mean, median and standard deviation of the volumes of water that can be contained in the containers?

In [3]:
no_of_items=10
lower_limit=5
upper_limit=25

In [4]:
np.random.seed(1)

In [5]:
values=np.random.random_integers(lower_limit, upper_limit, no_of_items)

C:\Users\Ankit Bhatia\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(5, 25 + 1) instead
  """Entry point for launching an IPython kernel.


In [6]:
values

array([10, 16, 17, 13, 14, 16, 10, 20,  5, 21])

In [7]:
values.ndim

1

In [8]:
values.size

10

In [9]:
values.dtype

dtype('int32')

In [10]:
values.shape

(10,)

In [11]:
containers=values.reshape(5,2)

In [12]:
containers

array([[10, 16],
       [17, 13],
       [14, 16],
       [10, 20],
       [ 5, 21]])

In [13]:
containers.ndim

2

In [14]:
radius=containers[:,0]

In [15]:
radius

array([10, 17, 14, 10,  5])

In [16]:
height=containers[:,1]

In [17]:
height

array([16, 13, 16, 20, 21])

In [18]:
volume=np.pi*(radius**2)*height

In [19]:
volume

array([ 5026.54824574, 11802.96359954,  9852.03456166,  6283.18530718,
        1649.33614313])

In [20]:
total_volume=volume.sum()

In [21]:
total_volume

34614.06785725234

In [22]:
max_volume=volume.max()

In [23]:
max_volume

11802.963599536852

In [24]:
index_of_max_volume=volume.argmax()

In [25]:
index_of_max_volume

1

In [26]:
index_of_min_vol=volume.argmin()

In [27]:
index_of_min_vol

4

In [28]:
min_vol=volume.min()

In [29]:
min_vol

1649.3361431346414

In [30]:
# #25 cards numbered 1 through 25 are randomly distributed equally amongst 5 people. 
# Find the sum of cards for each person such that for the 1st person, the sum is the value of 1st 
# card minus the sum of rest of the cards; for the 2nd person, the sum is the value of 2nd card 
# minus the sum of rest of the cards, and so on. The person for whom the sum of the cards is
# greatest will be the winner. Find the winner.

In [31]:
np.random.seed(4)

In [32]:
no_of_cards=np.random.randint(1,26,25)

In [33]:
no_of_cards

array([15, 24,  6,  2,  9, 24,  9, 19, 10,  8, 14, 24, 24,  9,  5, 19, 13,
        7, 11, 21,  4,  1, 24, 22, 22])

In [34]:
np.random.shuffle(no_of_cards)
no_of_cards

array([ 9, 19, 24, 24, 24, 24, 22, 19,  9, 11,  4, 13, 24, 14,  2, 21, 15,
        1,  7, 10,  5,  6, 22,  9,  8])

In [35]:
#OR
np.random.seed(2)

In [36]:
number_of_cards=np.arange(1,26)

In [37]:
number_of_cards

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [38]:
#lets shuffle these numbers
np.random.shuffle(number_of_cards)

In [39]:
number_of_cards

array([15,  1, 18,  7, 24, 10,  4, 17, 13, 23,  5, 11,  6, 20,  2,  3,  8,
       22, 21, 19, 12, 25, 14, 16,  9])

In [40]:
reshaped_numbers=number_of_cards.reshape(5,5)
reshaped_numbers

array([[15,  1, 18,  7, 24],
       [10,  4, 17, 13, 23],
       [ 5, 11,  6, 20,  2],
       [ 3,  8, 22, 21, 19],
       [12, 25, 14, 16,  9]])

In [41]:
I=np.eye(5,5)

In [42]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
diagonal_matrix=I*reshaped_numbers

In [44]:
diagonal_matrix

array([[15.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.,  0.],
       [ 0.,  0.,  6.,  0.,  0.],
       [ 0.,  0.,  0., 21.,  0.],
       [ 0.,  0.,  0.,  0.,  9.]])

In [45]:
U=np.ones((5,5))

In [46]:
U

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
I_minus_U=I-U

In [48]:
I_minus_U

array([[ 0., -1., -1., -1., -1.],
       [-1.,  0., -1., -1., -1.],
       [-1., -1.,  0., -1., -1.],
       [-1., -1., -1.,  0., -1.],
       [-1., -1., -1., -1.,  0.]])

In [49]:
negative_diagonal_matrix=(I_minus_U)*reshaped_numbers

In [50]:
negative_diagonal_matrix

array([[  0.,  -1., -18.,  -7., -24.],
       [-10.,   0., -17., -13., -23.],
       [ -5., -11.,   0., -20.,  -2.],
       [ -3.,  -8., -22.,   0., -19.],
       [-12., -25., -14., -16.,   0.]])

In [51]:
combined_matrix=(diagonal_matrix)+(negative_diagonal_matrix)

In [52]:
combined_matrix

array([[ 15.,  -1., -18.,  -7., -24.],
       [-10.,   4., -17., -13., -23.],
       [ -5., -11.,   6., -20.,  -2.],
       [ -3.,  -8., -22.,  21., -19.],
       [-12., -25., -14., -16.,   9.]])

In [53]:
#row_wise addition'
sum_across_columns=combined_matrix.sum(axis=1)

In [54]:
winner=np.argmax(sum_across_columns)

In [55]:
winner

3

In [56]:
# You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.

In [57]:

start_point=0
end_point=5
no_of_parts=10
#to find equidistant points
np.linspace(0,5,10)



array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [58]:
# # linspace is often confused with arange. 
# arange produces a NumPy array that goes from start to end (excluded) by using 
# the third argument as a step. linspace produces a NumPy array that contains 
# equidistant points from start to end (included) by using the third argument 
# as the number of points to be calculated between the two ends.

In [59]:
# #ARRAYS
# The central feature of NumPy is the array object class. Arrays are similar to lists in Python,
# except that every element of an array must be of the same type, typically a numeric type like
# float or int

In [60]:
a=np.array([1.0,2.0,3.0,4.0],dtype=float)

In [61]:
a

array([1., 2., 3., 4.])

In [62]:
type(a)

numpy.ndarray

In [63]:
#Array elements are accessed, sliced, and manipulated just like lists
a[:2]

array([1., 2.])

In [64]:
a[3]


4.0

In [65]:
#multidimensional arays
b=np.array([[1,2,3],[4,5,6]])

In [66]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.full((4,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [68]:
np.random.seed(5)
np.random.random(5)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [69]:
np.random.seed(5)
np.random.rand(5)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [70]:

np.random.randint(1,10,5)

array([8, 1, 1, 8, 2])

In [71]:
np.random.randint(1,10,5)

array([6, 8, 1, 2, 5])

In [72]:
#array indexing
a=np.array([[1,2,3],[4,5,6]])

In [73]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):

In [75]:
b=a[:,0:2]

In [76]:
b

array([[1, 2],
       [4, 5]])

In [77]:
#You can also mix integer indexing with slice indexing. 
#However, doing so will yield an array of lower rank than the original array.

In [78]:
x=np.array([[[1,2],[4,5]],[[7,8],[9,10]]])
print(x)
print(x.shape)
p=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(p)
print(p.shape)
print(p.ndim)
x.ndim


[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]]]
(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


3

In [79]:
# In Numpy, dimension, axis/axes, shape are related and sometimes similar concepts:

# dimension
# In Mathematics/Physics, dimension or dimensionality is informally defined as
#the minimum number of coordinates needed to specify any point within a space. 
#But in Numpy, according to the numpy doc, it's the same as axis/axes:

# In Numpy dimensions are called axes. The number of axes is rank.

# In [3]: a.ndim  # num of dimensions/axes, *Mathematics definition of dimension*
# Out[3]: 2
# axis/axes
# the nth coordinate to index an array in Numpy. And multidimensional arrays can have one index per axis.

# In [4]: a[1,0]  # to index `a`, we specific 1 at the first axis and 0 at the second axis.
# Out[4]: 3  # which results in 3 (locate at the row 1 and column 0, 0-based index)
# shape
# describes how many data (or the range) along each available axis.

# In [5]: a.shape
# Out[5]: (2, 2)  # both the first and second axis have 2 (columns/rows/pages/blocks/...) data

In [80]:
x
print(x)

x2=[[[1,2,3],[4,5,6]],[7,8,9]]
print(x2)

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]]]
[[[1, 2, 3], [4, 5, 6]], [7, 8, 9]]


In [81]:
three_d=x.reshape(1,4,2)
print(three_d)
print (three_d.shape)


[[[ 1  2]
  [ 4  5]
  [ 7  8]
  [ 9 10]]]
(1, 4, 2)


In [82]:
three_d[0]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10]])

In [83]:
three_d[0,0]

array([1, 2])

In [84]:
three_d[0,0,0]

1

In [85]:
print("sum along 1st dimension is:" ,(np.sum(three_d,axis=0)))
print("sum along 2nd dimension is:",(np.sum(three_d,axis=1)))
print("sum along 3rd dimension is:", (np.sum(three_d,axis=2)))



sum along 1st dimension is: [[ 1  2]
 [ 4  5]
 [ 7  8]
 [ 9 10]]
sum along 2nd dimension is: [[21 25]]
sum along 3rd dimension is: [[ 3  9 15 19]]


In [86]:
x.ndim

3

In [87]:
np.shape(x)

(2, 2, 2)

In [88]:
y=np.zeros((2, 3, 4))

In [89]:
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [90]:
y.ndim

3

In [91]:
np.shape(y)

(2, 3, 4)

In [92]:
#creating similar list of arrayy
z=[[[0,0,0,0],[0,0,0,0],[0,0,0,0]],[[0,0,0,0],[0,0,0,0],[0,0,0,0]]]

In [93]:
z

[[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
 [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]]

In [94]:
np.rank(z)

C:\Users\Ankit Bhatia\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  """Entry point for launching an IPython kernel.


3

In [95]:
#First level of this compound list 'z' has exactly 2 elements, just as first dimension of array y (# of rows). 
#Each of these elements is itself list with 3 elements, which is equal to second dimension of y (# of columns). 
#Finally, the most nested lists have 4 elements each, same as third dimension of y (depth/# of colors).

In [96]:
# #Array INDEXING and Slicing
# You can also mix integer indexing with slice indexing. 
# However, doing so will yield an array of lower rank than the original array
s=np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]])

In [97]:
s

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
# # Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
w1=s[1,:]
print(w1) #reduced rank
print("rank of w1 is:", np.rank(w1), "and shape is", w1.shape, "transpose is:", w1.T)
w2=s[1:2,:]
print(w2)
print("rank of w2 is:", np.rank(w2), "and shape is", w2.shape)

[4 5 6 7]
rank of w1 is: 1 and shape is (4,) transpose is: [4 5 6 7]
[[4 5 6 7]]
rank of w2 is: 2 and shape is (1, 4)


C:\Users\Ankit Bhatia\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  import sys
C:\Users\Ankit Bhatia\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  # Remove the CWD from sys.path while we load stuff.


In [99]:
v1=s[:,1]
print(v1) #reduced rank
print("rank of v1 is:", np.rank(v1), "and shape is", v1.shape, "transpose is:", v1.T)
v2=s[:,1:2]
print(v2)
print("rank of v2 is:", np.rank(v2), "and shape is", v2.shape)

[2 5 9]
rank of v1 is: 1 and shape is (3,) transpose is: [2 5 9]
[[2]
 [5]
 [9]]
rank of v2 is: 2 and shape is (3, 1)


C:\Users\Ankit Bhatia\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Ankit Bhatia\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  


In [100]:
# INTEger ARRay INDEXing
# When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. 
# In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [101]:

d=np.array([[1,2],[3,4],[5,6],[7,8]])
d

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [102]:
ee=np.array([d[0,1],d[1,1],d[3,0]])
gg=d[[0,1,3],[1,1,0]]
print(ee)
print("shape of ee is :", ee.shape)
print(gg)
print("shape of gg is", gg.shape)

[2 4 7]
shape of ee is : (3,)
[2 4 7]
shape of gg is (3,)


In [103]:
# selecting or mutating one element from each row of a matrix:
tt=np.array([0,1])

In [104]:
np.arange(4)

array([0, 1, 2, 3])

In [105]:
print(d[tt,np.arange(2)])

[1 4]


In [106]:
# Boolean array indexing: 
# this type of indexing is used to select the elements of an array that satisfy some condition

bool_index=(s>3) #note 's'
print(type(bool_index))
print(s[bool_index])
print(np.unique(s[bool_index]))



<class 'numpy.ndarray'>
[ 4  4  5  6  7  8  9 10 11]
[ 4  5  6  7  8  9 10 11]


In [107]:
g=np.array([[5,6],[2,3]])
h=np.array([[1,4],[0,7]])

In [108]:
g

array([[5, 6],
       [2, 3]])

In [109]:
h

array([[1, 4],
       [0, 7]])

In [110]:
e=np.array([10,10])
f=np.array([100,100])

In [111]:
print(e)
g.ndim

[10 10]


2

In [112]:
print(f)
f.shape


[100 100]


(2,)

In [113]:
print(f.ndim)

1


In [114]:
print(e.dot(g))
print(g.dot(e))
print(h.dot(f))
print(f.dot(h))

#note the differences among output

[70 90]
[110  50]
[500 700]
[ 100 1100]


In [115]:
# # # numpy.dot:

# # For 2-D arrays it is equivalent to matrix multiplication, and for 1-D arrays to inner product of vectors (without complex conjugation). For N dimensions it is a sum product over the last axis of a and the second-to-last of b:

# # numpy.inner:

# # Ordinary inner product of vectors for 1-D arrays (without complex conjugation), in higher dimensions a sum product over the last axes.

# # (Emphasis mine.)

# # As an example, consider this example with 2D arrays:

# # >>> a=np.array([[1,2],[3,4]])
# # >>> b=np.array([[11,12],[13,14]])
# # >>> np.dot(a,b)
# # array([[37, 40],
# #        [85, 92]])
# # >>> np.inner(a,b)
# # array([[35, 41],
# #        [81, 95]])


# # A = [[a1,b1],[c1,d1]]
# B = [[a2,b2],[c2,d2]]
# numpy.inner(A,B)
# array([[a1*a2 + b1*b2, a1*c2 + b1*d2],
#        [c1*a2 + d1*b2, c1*c2 + d1*d2])

In [125]:
#August 22
#bradcasting
h=np.array([[1,2,3],[4,5,6],[7,8,9]])
k=np.array([1,2,3])
v=np.empty_like(h)
for i in range (3):
    v[i,:]=h[i,:]+k
print(v)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [127]:
vv=np.tile(v, 4)
print(vv)

[[ 2  4  6  2  4  6  2  4  6  2  4  6]
 [ 5  7  9  5  7  9  5  7  9  5  7  9]
 [ 8 10 12  8 10 12  8 10 12  8 10 12]]


In [132]:
g=v+h
print(g)
gg=h+v
print(gg)

[[ 3  6  9]
 [ 9 12 15]
 [15 18 21]]
[[ 3  6  9]
 [ 9 12 15]
 [15 18 21]]


In [134]:
c=np.array([1,2,3])

In [137]:
d=np.array([4,5])

In [143]:
print(np.reshape(c,(3,1))*d)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [147]:
j=np.array([[6,4,2],[5,8,9]])

In [149]:
c+j

array([[ 7,  6,  5],
       [ 6, 10, 12]])